### ISSUE TITLE
Bad error message with invalid input

### ISSUE THREAD

**Issue by yamikuronue** [yamikuronue/SockLogiDice#4]
Input:
```
@yamibot roll @index&zwnj;d@index
```

Expected output: Some user-friendly text about invalid dice. 

Actual Output:
```
An unexpected error `Cannot read property 'join' of undefined` occured and your commands could not be processed!
```

**Comment by AccaliaDeElementia** [comment]
Hmm.....

looks like the error is coming from [here](https://github.com/yamikuronue/SockLogiDice/blob/e0f67544ca281713f3d57ba74f4bc4f6127a12ca/src/view.js#L54)

in that line `result.rolls` is undefined so the join there fails.

Still investigating *why* result.rolls is undefined.
