### ISSUE TITLE
Make <details> and <summary> tags configurable

### ISSUE THREAD

**Issue by michaelpfaff** [yamikuronue/SockLogiDice#9]
This is a feature request to disable / enable the <details> and <summary> tags in the output for forums using the code that do not support those. 

Thanks for the amazing plugin!

**Comment by yamikuronue** [comment]
Done

**Comment by michaelpfaff** [comment]
Whoa! That was quick! Should I just update the plugin and leave my config the same for this to take effect?

**Comment by yamikuronue** [comment]
Yup, that should do it :) By default the spoiler tags are off

**Comment by michaelpfaff** [comment]
Awesome! Thanks! I should be able to use the following to update, yes?  

`npm update -g sock-logidice`

**Comment by yamikuronue** [comment]
Probably? Make sure it says it installed 2.0.0. You may have to uninstall and reinstall if not.

**Comment by michaelpfaff** [comment]
Sounds good! Thanks again!
